---
- name: Configure VM and deploy container
  hosts: vm
  become: true
  vars_files:
    - secrets.yml

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Podman
      ansible.builtin.apt:
        name: podman
        state: present

#    - name: Login to Azure Container Registry
#      containers.podman.podman_login:
#        registry: acrcp2denisse.azurecr.io
#        username: acrcp2denisse
#        password: "{{ acr_password }}"

    - name: Run nginx container
      containers.podman.podman_container:
        name: webvm
        image: acrcp2denisse.azurecr.io/webvm:casopractico2
        state: started
        publish:
          - "8080:80"
        recreate: true

- name: Deploy application to AKS
  hosts: localhost
  connection: local
  vars_files:
    - secrets.yml

  tasks:
    - name: Create Kubernetes namespace
      include_role:
        name: aks